### ISSUE TITLE
Lowering required CMake version for Ubuntu 20.04?

### ISSUE THREAD

**Issue by kjrusscher** [eclipse-zenoh/zenoh-cpp#7] opened 2022-12-19 10:47 UTC
The required cmake version for this repo is set to 3.21. 

The package manager in Ubuntu 20.04LTS has cmake version 3.16. The required cmake version for Zenoh-C is version 3.10. 

My question is; is 3.21 a deliberate choice? If not, could it be set to 3.16 so we don't have to recompile cmake on Ubuntu 20.04?

**Comment by Mallets** [comment] 2022-12-19 17:01
Fixed by https://github.com/eclipse-zenoh/zenoh-cpp/pull/9. CMake version is now set to 3.16.

**Comment by kjrusscher** [comment] 2022-12-20 08:48
I've tested this and it does not work. The error that I get is: `add_library cannot create ALIAS target "zenohc::lib" because target
  "__zenohc_lib" is imported but not globally visible.`. This is a CMake error. The problem is caused by lines 42 and 46 in `/usr/local/lib/cmake/zenohc/zenohcConfig.cmake`, so a file that is generated by installing zenoh-c. [Here](https://discourse.cmake.org/t/alias-and-not-globally-visible-targets/6305) is explained how the problem can be solved, but that has to be done in how zenoh-c generates files.

My suggestion is to revert the change and go back to CMake 3.21 (for now) since that works.

**Comment by milyin** [comment] 2022-12-20 09:05
Yes, I've also encountered the same problem yesterday after the version rollback. The fix was to use absolute path in CMAKE_INSTALL_PREFIX - seems that old version of cmake treats relative path as relative to CMakeLists.txt location and newer version treats is as relative to current build directory.
So for now I think the better way to fix it is to just update readme, removing the recomendation to use relative path

**Comment by kjrusscher** [comment] 2022-12-20 09:31
Hi Milyin. Do you mean to use `-DCMAKE_INSTALL_PREFIX=/usr/local`? I did use that and it resulted in the error above.

**Comment by milyin** [comment] 2022-12-20 09:40
> Hi Milyin. Do you mean to use `-DCMAKE_INSTALL_PREFIX=/usr/local`? I did use that and it resulted in the error above.

That's strange. I used /home/username/local (to avoid working on root) both for zenoh-c and zenoh-cpp and it worked. I'll check it again

**Comment by kjrusscher** [comment] 2022-12-20 09:51
I tried the following just now: (username is my own user name)
```
git clone https://github.com/eclipse-zenoh/zenoh-c.git && \
cd zenoh-c && mkdir -p build && cd build && \
cmake .. -DCMAKE_INSTALL_PREFIX=/home/username/local && \
cmake --build . --target install && \
cd ../.. && \
git clone https://github.com/eclipse-zenoh/zenoh-cpp.git && \
cd zenoh-cpp && mkdir -p build && cd build && \
cmake .. -DCMAKE_INSTALL_PREFIX=/home/username/local && \
cmake --build . --target install 
```

This results in the error:
```
CMake Error at /home/username/local/lib/cmake/zenohc/zenohcConfig.cmake:42 (add_library):
  add_library cannot create ALIAS target "zenohc::static" because target
  "__zenohc_static" is imported but not globally visible.
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)


CMake Error at /home/username/local/lib/cmake/zenohc/zenohcConfig.cmake:46 (add_library):
  add_library cannot create ALIAS target "zenohc::lib" because target
  "__zenohc_lib" is imported but not globally visible.
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)
```

I'm using Ubuntu 20.04 with CMake 3.16.3

**Comment by milyin** [comment] 2022-12-20 10:07
For me this sequence works well on mac (cmake 3.25.1), Ubuntu 22.04 (cmake 3.22.1), Ubuntu 20.04 (cmake 3.23.2).
Seems that the problem is in some bug in old cmake version. Maybe it's mentioned here https://discourse.cmake.org/t/alias-and-not-globally-visible-targets/6305

**Comment by kjrusscher** [comment] 2022-12-20 10:36
I think it's a problem with CMake 3.16. It can be solved by editing zenohcConfig.cmake that is generated when compiling zenoh-c. 

Lines 41 and 45 have the functions `add_library(__zenohc_static STATIC IMPORTED)` and `add_library(__zenohc_lib STATIC IMPORTED)`. Adding `GLOBAL` to those functions solves the problem.

I will try to change the generation of those files in zenoh-c and upload them as a pull request.

**Comment by milyin** [comment] 2023-09-19 09:14
Real cmake 3.16 doesn't work with current cmake files, despite that 3.20 works ok with 3.16 mode.

**Comment by milyin** [comment] 2023-10-24 08:56
Fixed in https://github.com/eclipse-zenoh/zenoh-cpp/pull/75

**Closed by milyin** 2023-10-24 08:56 UTC
